### PR TITLE
U/jbkalmbach/data products to science

### PR DESCRIPTION
**Pull request by jbkalmbach**
Starting PR for tomorrow's lesson. Open for comments now but still a draft since it's just the code outline without the necessary commentary yet.

### CODE REVIEW

**Comment by kadrlica** [comment]
Thanks @jbkalmbach. Happy to take a look whenever you think is useful. Feel free to add me as a reviewer.

**Comment by jbkalmbach** [comment]
Thanks @kadrlica If you have some time in the morning for a quick look that'd be great. @mrawls  and I walked through it today so no worries if you don't.

**Comment by kadrlica** [comment]
Thanks, I'll take a look

**Review by kadrlica — APPROVED** [review]
Looks good! I'm going to merge and link.

Might want to talk about forced photometry at the end of the notebook (i.e., setting upper limits for exposures without detections).

**Pull request merged**
